apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: kubevirt
spec:
  version: v0.1.9
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
